# Generated by Django 3.0.8 on 2020-09-07 10:57

import datetime
from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MySuibi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='随笔标题', max_length=50, verbose_name='随笔标题')),
                ('type', models.CharField(default='', help_text='随笔类型', max_length=30, verbose_name='随笔类型')),
                ('content', mdeditor.fields.MDTextField()),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '我的随笔',
                'verbose_name_plural': '我的随笔',
            },
        ),
    ]
