# Generated by Django 3.0.8 on 2020-09-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysuibi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysuibi',
            name='type',
            field=models.CharField(blank=True, default='', help_text='随笔类型', max_length=30, null=True, verbose_name='随笔类型'),
        ),
    ]
