# Generated by Django 3.0.8 on 2020-09-22 20:59

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysuibi', '0003_auto_20200908_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysuibi',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='path/to', verbose_name='传图片'),
        ),
    ]
