# Generated by Django 3.0.8 on 2020-09-23 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysuibi', '0005_mysuibi_geshi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysuibi',
            old_name='geshi',
            new_name='mode',
        ),
    ]
