# Generated by Django 3.0.8 on 2020-09-07 10:40

import datetime
from django.db import migrations, models
import mdeditor.fields
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='博客标题', max_length=50, verbose_name='博客标题')),
                ('image', stdimage.models.StdImageField(upload_to='path/to', verbose_name='传图片')),
                ('content', mdeditor.fields.MDTextField()),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '我的博客',
                'verbose_name_plural': '我的博客',
            },
        ),
    ]
