# Generated by Django 3.0.8 on 2020-09-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_remove_myblog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='type',
            field=models.CharField(default='', help_text='博客类型', max_length=50, verbose_name='博客类型'),
        ),
    ]
