# Generated by Django 3.0.8 on 2020-09-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_myblog_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myblog',
            options={'ordering': ['add_time'], 'verbose_name': '我的博客', 'verbose_name_plural': '我的博客'},
        ),
    ]
