# Generated by Django 3.0.8 on 2020-09-07 19:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myblog', '0003_myblog_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='用户', max_length=30, verbose_name='用户')),
                ('email', models.CharField(default='', help_text='用户邮箱', max_length=30, verbose_name='用户邮箱')),
                ('content', mdeditor.fields.MDTextField()),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('comment_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myblog.MyBlog', verbose_name='评论对象')),
            ],
            options={
                'verbose_name': '评论列表',
                'verbose_name_plural': '评论列表',
                'ordering': ['add_time'],
            },
        ),
    ]
