# Generated by Django 3.0.8 on 2020-09-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlist',
            name='email',
            field=models.CharField(blank=True, default='', help_text='用户邮箱', max_length=30, null=True, verbose_name='用户邮箱'),
        ),
    ]
