# Generated by Django 3.0.8 on 2020-09-30 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20200929_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentlist_blog',
            options={'ordering': ['add_time'], 'verbose_name': '博客评论列表', 'verbose_name_plural': '博客评论列表'},
        ),
        migrations.AlterModelOptions(
            name='commentlist_suibi',
            options={'ordering': ['add_time'], 'verbose_name': '随笔评论列表', 'verbose_name_plural': '随笔评论列表'},
        ),
    ]
